### ISSUE TITLE
Req: add telegram topics

### ISSUE THREAD

**Issue by alexunderboots** [solyard/weasel#11]
please add telegram topics support
`create_task(context.bot.send_message(text=f'{text}', chat_id=channel, message_thread_id=thread, disable_web_page_preview=True, parse_mode=parse_mode))`
**message_thread_id=thread,**

**Comment by solyard** [comment]
Hi. I'm working on new version of bot for now. Will release new features in January 2024. Does this request are actual for now?

**Comment by solyard** [comment]
@alexunderboots while bot under development you can use a new branch to get functionality for Telegram Topics: https://github.com/solyard/weasel/tree/feature/telegram-topics
